version: "3"

services:
    server:
        build:
            context: .
        ports:
            - 5000:5000
        volumes:
            - .:/app:ro
        #    - /<local path>:/data/archive
        links:
            - elastic

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
        ports:
            - 9200:9200
        #volumes:
        #    - /<local path>:/usr/share/elasticsearch/data

    #fuseki:
    #   image: fuseki:2

    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./static:/www/static:ro
            - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - server


